name: Trigger Target Repo Workflow

on:
  push:
    branches:
      - main
# env:
#   GITHUB_TOKEN: ${{ secrets.GHAPPID_TOKEN }}
    
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install -y curl
        
      - name: Debugging - Print Environment Variables
        run: env
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}

      - name: Trigger Workflow in Same Repository
        uses: peter-evans/repository-dispatch@v3 #rancher/repository-dispatch@v1
        with:
            #token: ${{ secrets.TARGET_REPO_PAT }}
            event-type: my_event_type
            #repository: Stuti-Kumar/BeautifulFlower
            #payload: '{"message":"hello world"}'
      
      - name: Trigger Workflow in Target Repository
        uses: peter-evans/repository-dispatch@v3 
        with:
            token: ${{ secrets.TARGET_REPO_PAT }}
            event-type: my_event_type
            repository: Stuti-Kumar/BeautifulFlower
            client-payload: '{"message":"hello world"}'

      - name: Trigger via Code
        shell: /usr/bin/bash -e {0}
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |      
           curl -X POST 
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: token ${{ secrets.TARGET_REPO_PAT }}"
             -H "X-GitHub-Api-Version: 2022-11-28" 
             https://api.github.com/repos/Stuti-Kumar/BeautifulFlower/actions/workflows/target_workflow_new.yml/dispatches
             -d '{"ref":"main"}'   

        # run: |
        #   curl -X POST \
        #     -H "Accept: application/vnd.github.v3+json" \
        #     -H "Authorization: token ${{ secrets.GHAPPID_TOKEN }}" \
        #     https://github.deere.com/mbsd/EnterpriseTools/blob/dev/.github/workflows/GHAPipeline.yml
        #       -d '{"ref":"dev"}'
        # https://github.deere.com/mbsd/EnterpriseTools/blob/trigger-workflow/.github/workflows/target_workflow.yml/dispatches \

          #         echo "Using token: $GITHUB_TOKEN"
          # curl -X POST \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   -H "Authorization: token ${{ secrets.TARGETREPOPAT_FINE }}" \
          #   -d '{"ref":"trigger-workflow"}' \
          #   https://api.github.com/repos/mbsd/EnterpriseTools/actions/workflows/target_workflow.yml/dispatches   
